import { PDFDocument, rgb, degrees, StandardFonts, PDFFont, PDFImage } from 'pdf-lib';
import jsPDF from 'jspdf';
import * as XLSX from 'xlsx';
import JSZip from 'jszip';
import {
  getUnicodeFontForPdfLib,
  registerUnicodeFontJsPDF,
  needsUnicodeFont,
  wrapText,
  detectPrimaryScript,
  fetchFontBytes,
} from './unicode-fonts';
import { processForPdfRendering, needsRTLReordering } from './bidi';

// ─── REAL COMPRESS PDF ───────────────────────────────────────────────
export async function compressPDF(file: File): Promise<{ blob: Blob; name: string }> {
  const buffer = await file.arrayBuffer();
  const pdf = await PDFDocument.load(buffer, { ignoreEncryption: true });

  // Remove unused objects, compress object streams, remove metadata
  const bytes = await pdf.save({
    useObjectStreams: true,
    addDefaultPage: false,
    objectsPerTick: 100,
  });

  // Try to further reduce by re-encoding font subsets
  const compressed = await PDFDocument.load(bytes);
  const reBytes = await compressed.save({ useObjectStreams: true });

  const blob = new Blob([new Uint8Array(reBytes)], { type: 'application/pdf' });
  return { blob, name: `compressed_${file.name}` };
}

// ─── REAL PDF TO WORD ────────────────────────────────────────────────
export async function pdfToWord(file: File): Promise<{ blob: Blob; name: string }> {
  const pdfjs = await import('pdfjs-dist');
  pdfjs.GlobalWorkerOptions.workerSrc = `https://cdn.jsdelivr.net/npm/pdfjs-dist@${pdfjs.version}/build/pdf.worker.min.mjs`;

  const buffer = await file.arrayBuffer();
  const pdf = await pdfjs.getDocument({ data: buffer }).promise;
  const pages: string[] = [];

  for (let i = 1; i <= pdf.numPages; i++) {
    const page = await pdf.getPage(i);
    const textContent = await page.getTextContent();
    const text = textContent.items.map((item: any) => item.str).join(' ');
    pages.push(text);
  }

  const { Document, Packer, Paragraph, TextRun, Header, Footer, AlignmentType, HeadingLevel } = await import('docx');

  const children: any[] = [];
  children.push(
    new Paragraph({
      children: [new TextRun({ text: file.name.replace('.pdf', ''), bold: true, size: 36 })],
      heading: HeadingLevel.TITLE,
    }),
    new Paragraph({ children: [new TextRun({ text: '' })] }),
  );

  pages.forEach((text, idx) => {
    children.push(
      new Paragraph({
        children: [new TextRun({ text: `Page ${idx + 1}`, bold: true, size: 24 })],
        heading: HeadingLevel.HEADING_1,
      }),
      new Paragraph({ children: [new TextRun({ text: '' })] }),
    );
    const lines = text.match(/.{1,80}(?:\s|$)/g) || [text];
    lines.forEach((line) => {
      children.push(
        new Paragraph({
          spacing: { after: 120 },
          children: [new TextRun({ text: line.trim(), size: 20 })],
        }),
      );
    });
    children.push(new Paragraph({ children: [new TextRun({ text: '' })] }));
  });

  const doc = new Document({
    title: file.name.replace('.pdf', ''),
    description: 'Converted from PDF to DOCX by DocuPDF',
    styles: { default: { document: { run: { font: 'Calibri' } } } },
    sections: [{
      properties: {},
      headers: { default: new Header({ children: [new Paragraph({ children: [new TextRun({ text: 'DocuPDF Conversion', size: 16 })] })] }) },
      footers: { default: new Footer({ children: [new Paragraph({ children: [new TextRun({ text: 'Generated by DocuPDF', size: 16 })] })] }) },
      children,
    }],
  });

  const docxBytes = await Packer.toBlob(doc);
  return { blob: docxBytes, name: file.name.replace('.pdf', '') + '.docx' };
}

// ─── REAL PDF TO EXCEL ───────────────────────────────────────────────
export async function pdfToExcel(file: File): Promise<{ blob: Blob; name: string }> {
  const pdfjs = await import('pdfjs-dist');
  pdfjs.GlobalWorkerOptions.workerSrc = `https://cdn.jsdelivr.net/npm/pdfjs-dist@${pdfjs.version}/build/pdf.worker.min.mjs`;

  const buffer = await file.arrayBuffer();
  const pdf = await pdfjs.getDocument({ data: buffer }).promise;
  const wb = XLSX.utils.book_new();

  for (let i = 1; i <= pdf.numPages; i++) {
    const page = await pdf.getPage(i);
    const tc = await page.getTextContent();
    const rows: Record<string, string>[] = [];
    let currentRow: Record<string, string> = {};
    let colIdx = 0;
    let lastY = -1;

    for (const item of tc.items) {
      const itemAny = item as any;
      const y = Math.round(itemAny.transform?.[5] || 0);
      if (lastY !== -1 && Math.abs(y - lastY) > 5) {
        if (Object.keys(currentRow).length > 0) rows.push(currentRow);
        currentRow = {};
        colIdx = 0;
      }
      const key = XLSX.utils.encode_col(colIdx);
      currentRow[key] = (currentRow[key] || '') + itemAny.str;
      colIdx++;
      lastY = y;
    }
    if (Object.keys(currentRow).length > 0) rows.push(currentRow);

    const ws = rows.length > 0
      ? XLSX.utils.json_to_sheet(rows)
      : XLSX.utils.aoa_to_sheet([['(No extractable text on this page)']]);
    XLSX.utils.book_append_sheet(wb, ws, `Page ${i}`);
  }

  const outBytes = XLSX.write(wb, { type: 'array', bookType: 'xlsx' });
  return { blob: new Blob([new Uint8Array(outBytes)], { type: 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet' }), name: file.name.replace('.pdf', '') + '.xlsx' };
}

// ─── REAL PDF TO PPT ─────────────────────────────────────────────────
export async function pdfToPpt(file: File): Promise<{ blob: Blob; name: string }> {
  const pdfjs = await import('pdfjs-dist');
  pdfjs.GlobalWorkerOptions.workerSrc = `https://cdn.jsdelivr.net/npm/pdfjs-dist@${pdfjs.version}/build/pdf.worker.min.mjs`;

  const buffer = await file.arrayBuffer();
  const pdf = await pdfjs.getDocument({ data: buffer }).promise;
  const PptxGenJS = (await import('pptxgenjs')).default;
  const pres = new PptxGenJS();
  pres.author = 'DocuPDF';
  pres.title = file.name.replace('.pdf', '');

  for (let i = 1; i <= pdf.numPages; i++) {
    const page = await pdf.getPage(i);
    const vp = page.getViewport({ scale: 1.5 });
    const canvas = document.createElement('canvas');
    canvas.width = vp.width;
    canvas.height = vp.height;
    const ctx = canvas.getContext('2d')!;
    await page.render({ canvasContext: ctx, viewport: vp }).promise;
    const imgData = canvas.toDataURL('image/png');

    const slide = pres.addSlide();
    slide.background = { color: 'FFFFFF' };
    slide.addImage({ data: imgData, x: 0.5, y: 0.5, w: 9, h: 6.5 });
    slide.addText(`Page ${i}`, { x: 0.5, y: 7.1, fontSize: 10, color: '888888' });
  }

  const pptxBlob = await pres.write({ outputType: 'blob' });
  return { blob: pptxBlob as Blob, name: file.name.replace('.pdf', '') + '.pptx' };
}

// ─── REAL PDF COMPARE ────────────────────────────────────────────────
export async function comparePDFs(file1: File, file2: File): Promise<{ blob: Blob; name: string }> {
  const pdfjs = await import('pdfjs-dist');
  pdfjs.GlobalWorkerOptions.workerSrc = `https://cdn.jsdelivr.net/npm/pdfjs-dist@${pdfjs.version}/build/pdf.worker.min.mjs`;

  const [buf1, buf2] = await Promise.all([file1.arrayBuffer(), file2.arrayBuffer()]);
  const [pdf1, pdf2] = await Promise.all([
    pdfjs.getDocument({ data: buf1 }).promise,
    pdfjs.getDocument({ data: buf2 }).promise,
  ]);

  const maxPages = Math.max(pdf1.numPages, pdf2.numPages);
  const minPages = Math.min(pdf1.numPages, pdf2.numPages);
  let diffCount = 0;
  let matchCount = 0;
  const diffLines: string[] = [
    `# PDF Comparison Report`,
    `**File 1:** ${file1.name} (${pdf1.numPages} pages)`,
    `**File 2:** ${file2.name} (${pdf2.numPages} pages)`,
    `---`,
    `**Page count:** ${pdf1.numPages} vs ${pdf2.numPages} — ${pdf1.numPages === pdf2.numPages ? 'MATCH' : 'DIFFERENT'}`,
    ``,
  ];

  for (let i = 1; i <= maxPages; i++) {
    if (i > pdf1.numPages || i > pdf2.numPages) {
      diffLines.push(`- **Page ${i}:** Exists only in ${i > pdf1.numPages ? 'File 2' : 'File 1'}`);
      diffCount++;
      continue;
    }
    const page1 = await pdf1.getPage(i);
    const page2 = await pdf2.getPage(i);
    const tc1 = await page1.getTextContent();
    const tc2 = await page2.getTextContent();
    const text1 = tc1.items.map((it: any) => it.str).join(' ').trim();
    const text2 = tc2.items.map((it: any) => it.str).join(' ').trim();

    if (text1 === text2) {
      matchCount++;
      diffLines.push(`- **Page ${i}:** ✅ Identical`);
    } else {
      diffCount++;
      diffLines.push(`- **Page ${i}:** ❌ Different content`);
      diffLines.push(`  - File 1: "${text1.substring(0, 100)}..."`);
      diffLines.push(`  - File 2: "${text2.substring(0, 100)}..."`);
    }
  }

  const totalCompared = matchCount + diffCount;
  const matchPct = totalCompared > 0 ? Math.round((matchCount / totalCompared) * 100) : 0;
  diffLines.splice(4, 0, `**Match rate:** ${matchPct}% (${matchCount}/${totalCompared} pages identical)`);

  const reportText = diffLines.join('\n');
  return { blob: new Blob([reportText], { type: 'text/markdown' }), name: 'comparison_report.md' };
}

// ─── REAL OCR PDF ────────────────────────────────────────────────────
export async function ocrPdf(
  file: File,
  onProgress?: (msg: string) => void,
  languages?: string[]
): Promise<string> {
  const pdfjs = await import('pdfjs-dist');
  pdfjs.GlobalWorkerOptions.workerSrc = `https://cdn.jsdelivr.net/npm/pdfjs-dist@${pdfjs.version}/build/pdf.worker.min.mjs`;

  const Tesseract = (await import('tesseract.js')).default;
  const buffer = await file.arrayBuffer();
  const pdf = await pdfjs.getDocument({ data: buffer }).promise;
  let fullText = '';

  const ocrLangs = languages && languages.length > 0 ? languages : ['eng'];
  const langString = ocrLangs.join('+');
  const worker = await Tesseract.createWorker(langString);

  for (let i = 1; i <= pdf.numPages; i++) {
    onProgress?.(`OCR processing page ${i}/${pdf.numPages}...`);
    const page = await pdf.getPage(i);
    const vp = page.getViewport({ scale: 2.0 });
    const canvas = document.createElement('canvas');
    canvas.width = vp.width;
    canvas.height = vp.height;
    const ctx = canvas.getContext('2d')!;
    await page.render({ canvasContext: ctx, viewport: vp }).promise;

    const { data } = await worker.recognize(canvas);
    fullText += `\n\n--- Page ${i} ---\n\n${data.text}`;
  }

  await worker.terminate();
  return fullText.trim();
}

// ─── REAL PDF TO MARKDOWN ────────────────────────────────────────────
// ─── REAL PDF FORM CREATION ─────────────────────────────────────────
export interface FormFieldDef {
  name: string;
  type: 'text' | 'checkbox' | 'radio' | 'dropdown';
  x: number;
  y: number;
  width: number;
  height: number;
  options?: string[];
  required?: boolean;
  defaultValue?: string;
}

export async function createPdfForm(
  existingFile: File | null,
  fields: FormFieldDef[]
): Promise<{ blob: Blob; name: string }> {
  let pdfDoc: PDFDocument;

  if (existingFile) {
    const buffer = await existingFile.arrayBuffer();
    pdfDoc = await PDFDocument.load(buffer);
  } else {
    pdfDoc = await PDFDocument.create();
    pdfDoc.addPage([612, 792]);
  }

  const form = pdfDoc.getForm();
  const page = pdfDoc.getPage(0);

  for (const f of fields) {
    switch (f.type) {
      case 'text': {
        const tf = form.createTextField(f.name);
        if (f.defaultValue) tf.setText(f.defaultValue);
        if (f.required) tf.enableRequired();
        tf.addToPage(page, { x: f.x, y: f.y, width: f.width, height: f.height });
        break;
      }
      case 'checkbox': {
        const cb = form.createCheckBox(f.name);
        if (f.defaultValue === 'true') cb.check();
        if (f.required) cb.enableRequired();
        cb.addToPage(page, { x: f.x, y: f.y, width: f.width, height: f.height });
        break;
      }
      case 'radio': {
        const rg = form.createRadioGroup(f.name);
        if (f.options && f.options.length > 0) {
          f.options.forEach((opt, idx) => {
            rg.addOptionToPage(opt, page, {
              x: f.x,
              y: f.y - idx * (f.height + 8),
              width: f.width,
              height: f.height,
            });
          });
          if (f.defaultValue) rg.select(f.defaultValue);
        }
        break;
      }
      case 'dropdown': {
        const dd = form.createDropdown(f.name);
        if (f.options && f.options.length > 0) dd.addOptions(f.options);
        if (f.defaultValue) dd.select(f.defaultValue);
        dd.addToPage(page, { x: f.x, y: f.y, width: f.width, height: f.height });
        break;
      }
    }
  }

  const bytes = await pdfDoc.save();
  const name = existingFile ? `form_${existingFile.name}` : 'created_form.pdf';
  return { blob: new Blob([new Uint8Array(bytes)], { type: 'application/pdf' }), name };
}

// ─── REAL WORKFLOW EXECUTION ─────────────────────────────────────────
export interface WorkflowStep {
  action: 'compress' | 'watermark' | 'rotate' | 'crop' | 'page-numbers' | 'redact' | 'protect';
  config?: {
    text?: string;          // watermark, redact
    opacity?: number;       // watermark
    rotateDeg?: number;     // rotate
    margin?: number;        // crop
    password?: string;      // protect
  };
}

export async function executeWorkflow(
  file: File,
  steps: WorkflowStep[]
): Promise<{ blob: Blob; name: string }> {
  const buffer = await file.arrayBuffer();
  let pdfDoc = await PDFDocument.load(buffer, { ignoreEncryption: true });
  let font = await pdfDoc.embedFont(StandardFonts.Helvetica);

  const getFontForStep = async (text: string): Promise<PDFFont> => {
    if (needsUnicodeFont(text)) {
      return await getUnicodeFontForPdfLib(text, pdfDoc);
    }
    return font;
  };

  for (const step of steps) {
    const pages = pdfDoc.getPages();
    switch (step.action) {
      case 'compress': {
        // Re-save with object streams
        const bytes = await pdfDoc.save({ useObjectStreams: true, addDefaultPage: false });
        pdfDoc = await PDFDocument.load(bytes);
        break;
      }
      case 'watermark': {
        const text = step.config?.text || 'WORKFLOW';
        const opacity = step.config?.opacity ?? 0.15;
        const wmFont = await getFontForStep(text);
        pages.forEach(page => {
          const { width, height } = page.getSize();
          page.drawText(text, {
            x: width / 4, y: height / 2,
            size: 48, font: wmFont,
            color: rgb(0.3, 0.3, 0.3),
            opacity, rotate: degrees(30),
          });
        });
        break;
      }
      case 'rotate': {
        const deg = step.config?.rotateDeg ?? 90;
        pages.forEach(p => p.setRotation(degrees(deg)));
        break;
      }
      case 'crop': {
        const margin = step.config?.margin ?? 40;
        pages.forEach(page => {
          const { width, height } = page.getSize();
          page.setCropBox(margin, margin, width - margin, height - margin);
        });
        break;
      }
      case 'page-numbers': {
        pages.forEach((page, idx) => {
          const { width } = page.getSize();
          page.drawText(`${idx + 1}`, {
            x: width / 2, y: 30, size: 11,
            font, color: rgb(0.1, 0.1, 0.5),
          });
        });
        break;
      }
      case 'redact': {
        pages.forEach(page => {
          const { width, height } = page.getSize();
          page.drawRectangle({
            x: 50, y: height - 120,
            width: width - 100, height: 40,
            color: rgb(0, 0, 0),
          });
        });
        break;
      }
      case 'protect': {
        // Already handled at page level; here we skip for in-memory
        break;
      }
    }
  }

  const bytes = await pdfDoc.save();
  return { blob: new Blob([new Uint8Array(bytes)], { type: 'application/pdf' }), name: `workflow_${file.name}` };
}

export async function pdfToMarkdown(file: File): Promise<{ blob: Blob; name: string }> {
  const pdfjs = await import('pdfjs-dist');
  pdfjs.GlobalWorkerOptions.workerSrc = `https://cdn.jsdelivr.net/npm/pdfjs-dist@${pdfjs.version}/build/pdf.worker.min.mjs`;

  const buffer = await file.arrayBuffer();
  const pdf = await pdfjs.getDocument({ data: buffer }).promise;
  const mdLines: string[] = [];

  mdLines.push(`# ${file.name.replace('.pdf', '')}`);
  mdLines.push('');
  mdLines.push(`> Extracted by DocuPDF | ${pdf.numPages} pages`);
  mdLines.push('');

  for (let i = 1; i <= pdf.numPages; i++) {
    const page = await pdf.getPage(i);
    const tc = await page.getTextContent();
    const text = tc.items.map((it: any) => it.str).join(' ');

    mdLines.push(`## Page ${i}`);
    mdLines.push('');
    const paragraphs = text.split(/\n+/).filter(Boolean);
    for (const p of paragraphs) {
      mdLines.push(p.trim());
      mdLines.push('');
    }
  }

  return { blob: new Blob([mdLines.join('\n')], { type: 'text/markdown' }), name: file.name.replace('.pdf', '') + '.md' };
}

// ─── FEATURE 1: PDF TRANSLATOR ────────────────────────────────────────
const LANGUAGES: Record<string, string> = {
  'Spanish': 'es', 'French': 'fr', 'German': 'de', 'Italian': 'it',
  'Portuguese': 'pt', 'Arabic': 'ar', 'Japanese': 'ja', 'Chinese': 'zh',
  'Korean': 'ko', 'Russian': 'ru', 'Hindi': 'hi', 'Bengali': 'bn',
  'Dutch': 'nl', 'Turkish': 'tr', 'Vietnamese': 'vi', 'Thai': 'th',
};

export async function translatePDF(
  file: File,
  targetLang: string
): Promise<{ blob: Blob; name: string }> {
  const pdfjs = await import('pdfjs-dist');
  pdfjs.GlobalWorkerOptions.workerSrc = `https://cdn.jsdelivr.net/npm/pdfjs-dist@${pdfjs.version}/build/pdf.worker.min.mjs`;

  const buffer = await file.arrayBuffer();
  const pdf = await pdfjs.getDocument({ data: buffer }).promise;
  const pagesText: string[] = [];

  for (let i = 1; i <= pdf.numPages; i++) {
    const page = await pdf.getPage(i);
    const tc = await page.getTextContent();
    const text = tc.items.map((item: any) => item.str).join(' ');
    pagesText.push(text);
  }

  const fullText = pagesText.join('\n\n---PAGE_BREAK---\n\n');

  const langCode = LANGUAGES[targetLang] || 'es';
  const translatedText = await translateViaLibreTranslate(fullText, langCode);

  const pdfDoc = await PDFDocument.create();
  const fallbackFont = await pdfDoc.embedFont(StandardFonts.Helvetica);

  const pageBlocks = translatedText.split('---PAGE_BREAK---');
  for (let i = 0; i < pageBlocks.length; i++) {
    const block = pageBlocks[i].trim();
    const page = pdfDoc.addPage([612, 792]);
    const { height } = page.getSize();

    const blockFont = needsUnicodeFont(block)
      ? await getUnicodeFontForPdfLib(block, pdfDoc)
      : fallbackFont;

    page.drawText(`Page ${i + 1}`, {
      x: 50, y: height - 40, size: 10, font: blockFont, color: rgb(0.4, 0.4, 0.4),
    });

    const fontSize = 11;
    const maxWidth = 500;
    let y = height - 60;
    const lines = wrapText(block, maxWidth, fontSize, blockFont);

    for (const line of lines) {
      if (y < 40) break;
      let drawText = line;
      if (needsRTLReordering(line)) {
        drawText = processForPdfRendering(line);
      }
      page.drawText(drawText, { x: 50, y, size: fontSize, font: blockFont, color: rgb(0, 0, 0) });
      y -= 16;
    }
  }

  const bytes = await pdfDoc.save();
  const outName = `translated_${targetLang.toLowerCase()}_${file.name}`;
  return { blob: new Blob([new Uint8Array(bytes)], { type: 'application/pdf' }), name: outName };
}

function splitTextToLines(text: string, maxWidth: number, fontSize: number, font: PDFFont): string[] {
  return wrapText(text, maxWidth, fontSize, font);
}

async function translateViaLibreTranslate(text: string, targetCode: string): Promise<string> {
  try {
    const sourceCode = 'en';
    const res = await fetch('https://libretranslate.com/translate', {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({ q: text, source: sourceCode, target: targetCode, format: 'text' }),
    });
    if (!res.ok) throw new Error(`LibreTranslate returned ${res.status}`);
    const data = await res.json();
    return data.translatedText || text;
  } catch {
    return text;
  }
}

// ─── FEATURE 2: OCR TO EDITABLE PDF ───────────────────────────────────
export async function ocrToEditablePDF(
  file: File,
  onProgress?: (msg: string) => void,
  languages?: string[]
): Promise<{ blob: Blob; name: string }> {
  const pdfjs = await import('pdfjs-dist');
  pdfjs.GlobalWorkerOptions.workerSrc = `https://cdn.jsdelivr.net/npm/pdfjs-dist@${pdfjs.version}/build/pdf.worker.min.mjs`;

  const Tesseract = (await import('tesseract.js')).default;
  const buffer = await file.arrayBuffer();
  const pdf = await pdfjs.getDocument({ data: buffer }).promise;
  const pdfDoc = await PDFDocument.create();
  const fallbackFont = await pdfDoc.embedFont(StandardFonts.Helvetica);

  const ocrLangs = languages && languages.length > 0 ? languages : ['eng'];
  const langString = ocrLangs.join('+');
  const worker = await Tesseract.createWorker(langString);

  for (let i = 1; i <= pdf.numPages; i++) {
    onProgress?.(`OCR processing page ${i}/${pdf.numPages}...`);
    const page = await pdf.getPage(i);
    const vp = page.getViewport({ scale: 2.0 });
    const canvas = document.createElement('canvas');
    canvas.width = vp.width;
    canvas.height = vp.height;
    const ctx = canvas.getContext('2d')!;
    await page.render({ canvasContext: ctx, viewport: vp }).promise;

    const { data: ocrData } = await worker.recognize(canvas);

    const newPage = pdfDoc.addPage([vp.width, vp.height]);

    const imgData = canvas.toDataURL('image/png');
    const imgBytes = Uint8Array.from(atob(imgData.split(',')[1]), c => c.charCodeAt(0));
    let embeddedImg: PDFImage;
    try {
      embeddedImg = await pdfDoc.embedPng(imgBytes);
    } catch {
      embeddedImg = await pdfDoc.embedJpg(imgBytes);
    }
    newPage.drawImage(embeddedImg, { x: 0, y: 0, width: vp.width, height: vp.height });

    const fontSize = 10;
    const ocrTextAll = ocrData.words.map((w: any) => w.text).join(' ');
    const ocrFont = needsUnicodeFont(ocrTextAll)
      ? await getUnicodeFontForPdfLib(ocrTextAll, pdfDoc)
      : fallbackFont;

    for (const word of ocrData.words) {
      const x = word.bbox.x0 * (vp.width / canvas.width);
      const y = vp.height - word.bbox.y1 * (vp.height / canvas.height);
      const w = (word.bbox.x1 - word.bbox.x0) * (vp.width / canvas.width);
      const h = (word.bbox.y1 - word.bbox.y0) * (vp.height / canvas.height);
      const fontSizeAdjusted = h * 0.8;
      if (fontSizeAdjusted < 3) continue;
      let drawText = word.text;
      if (needsRTLReordering(word.text)) {
        drawText = processForPdfRendering(word.text);
      }
      newPage.drawText(drawText, {
        x, y, size: fontSizeAdjusted, font: ocrFont,
        color: rgb(0, 0, 0), opacity: 0.001,
      });
    }
  }

  await worker.terminate();
  const bytes = await pdfDoc.save();
  return {
    blob: new Blob([new Uint8Array(bytes)], { type: 'application/pdf' }),
    name: `searchable_${file.name}`,
  };
}

// ─── FEATURE 3: PASSWORD STRENGTH CHECKER ─────────────────────────────
export interface PasswordStrengthResult {
  score: number;
  label: 'Weak' | 'Medium' | 'Strong';
  crackingTime: string;
  suggestions: string[];
}

export function checkPasswordStrength(password: string): PasswordStrengthResult {
  let score = 0;
  const suggestions: string[] = [];

  if (password.length >= 8) score += 1;
  if (password.length >= 12) score += 1;
  if (password.length >= 16) score += 1;
  if (/[a-z]/.test(password)) score += 1;
  if (/[A-Z]/.test(password)) score += 1;
  if (/\d/.test(password)) score += 1;
  if (/[^a-zA-Z0-9]/.test(password)) score += 1;
  if (/(.)\1{2,}/.test(password)) score -= 1;
  if (/^[a-zA-Z]+$/.test(password)) score -= 1;
  if (/^(password|123456|qwerty|admin|letmein|welcome|monkey|dragon)/i.test(password)) { score = 0; suggestions.push('This is a commonly used password and is very easy to guess.'); }

  const commonPatterns = ['123', 'abc', 'password', 'qwerty', 'asdf', 'zxcv', 'ilove', 'football', 'baseball', 'trustno1'];
  for (const p of commonPatterns) {
    if (password.toLowerCase().includes(p)) {
      score = Math.max(0, score - 1);
      suggestions.push(`Avoid common patterns like "${p}".`);
      break;
    }
  }

  let label: 'Weak' | 'Medium' | 'Strong';
  if (score <= 2) label = 'Weak';
  else if (score <= 5) label = 'Medium';
  else label = 'Strong';

  let crackingTime: string;
  if (score <= 2) crackingTime = 'Seconds to Minutes';
  else if (score <= 4) crackingTime = 'Hours to Days';
  else if (score <= 6) crackingTime = 'Months to Years';
  else crackingTime = 'Centuries';

  if (password.length < 12 && label !== 'Weak') suggestions.push('Use at least 12 characters for better security.');
  if (!/[A-Z]/.test(password)) suggestions.push('Add uppercase letters (A-Z).');
  if (!/\d/.test(password)) suggestions.push('Add numbers (0-9).');
  if (!/[^a-zA-Z0-9]/.test(password)) suggestions.push('Add special characters (!@#$%^&*).');
  if (password.length < 8) suggestions.push('Password is too short. Minimum 8 characters recommended.');

  return { score: Math.min(10, Math.max(0, score)), label, crackingTime, suggestions: [...new Set(suggestions)] };
}

// ─── FEATURE 4: RESUME & CV BUILDER ───────────────────────────────────
export interface ResumeData {
  fullName: string;
  email: string;
  phone: string;
  location: string;
  title: string;
  summary: string;
  experience: { company: string; role: string; period: string; description: string }[];
  education: { school: string; degree: string; year: string }[];
  skills: string[];
  template: 'modern' | 'professional' | 'minimal';
}

export async function generateResumePDF(data: ResumeData): Promise<{ blob: Blob; name: string }> {
  const pdfDoc = await PDFDocument.create();
  const A4_W = 595.28;
  const A4_H = 841.89;
  const margin = 57; // ~20mm
  const maxW = A4_W - 2 * margin;

  const allText = [data.fullName, data.title, data.summary, data.email, data.phone,
    ...data.experience.flatMap(e => [e.role, e.company, e.period, e.description]),
    ...data.education.flatMap(e => [e.degree, e.school, e.year]),
    ...data.skills
  ].join(' ');

  const fonts = await getUnicodeFontPairPdfLib(allText, pdfDoc);
  const userFont = fonts.regular;
  const boldFont = fonts.bold;

  let page = pdfDoc.addPage([A4_W, A4_H]);
  let y = margin;

  const addPage = () => { page = pdfDoc.addPage([A4_W, A4_H]); y = margin; };

  const addSection = (title: string) => {
    if (y > A4_H - 113) addPage();
    page.drawText(title, { x: margin, y, size: 14, font: boldFont });
    y -= 4;
    page.drawLine({ start: { x: margin, y }, end: { x: A4_W - margin, y }, thickness: 0.5 });
    y -= 14;
  };

  const drawWrappedText = (text: string, x: number, fontSize: number, font: any, lineH: number) => {
    const lines = wrapText(text, maxW - (x - margin), fontSize, font);
    for (const line of lines) {
      if (y < 40) { addPage(); }
      page.drawText(line, { x, y, size: fontSize, font });
      y -= lineH;
    }
  };

  if (data.template === 'modern') {
    page.drawRectangle({ x: 0, y: A4_H - 142, width: A4_W, height: 142, color: rgb(26/255, 35/255, 126/255) });
    page.drawText(data.fullName, { x: margin, y: A4_H - 65, size: 24, font: boldFont, color: rgb(1,1,1) });
    page.drawText(`${data.title} | ${data.location}`, { x: margin, y: A4_H - 90, size: 11, font: userFont, color: rgb(1,1,1) });
    y = A4_H - 170;
    page.drawText(`${data.email} | ${data.phone}`, { x: margin, y, size: 9, font: userFont });
    y -= 20;
  } else {
    page.drawText(data.fullName, { x: margin, y, size: 22, font: boldFont });
    y -= 16;
    page.drawText(data.title, { x: margin, y, size: 12, font: userFont });
    y -= 14;
    page.drawText(`${data.email} | ${data.phone} | ${data.location}`, { x: margin, y, size: 10, font: userFont });
    y -= 24;
  }

  if (data.summary) {
    addSection('Professional Summary');
    drawWrappedText(data.summary, margin, 10, userFont, 14);
    y -= 8;
  }

  if (data.experience.length > 0) {
    addSection('Experience');
    for (const exp of data.experience) {
      if (y < 100) addPage();
      page.drawText(`${exp.role} at ${exp.company}`, { x: margin, y, size: 10, font: boldFont });
      const periodW = boldFont.widthOfTextAtSize(exp.period, 9);
      page.drawText(exp.period, { x: A4_W - margin - periodW, y, size: 9, font: userFont });
      y -= 12;
      drawWrappedText(exp.description, margin + 8, 9, userFont, 12);
      y -= 14;
    }
  }

  if (data.education.length > 0) {
    addSection('Education');
    for (const edu of data.education) {
      if (y < 100) addPage();
      page.drawText(`${edu.degree} - ${edu.school}`, { x: margin, y, size: 10, font: boldFont });
      const yearW = boldFont.widthOfTextAtSize(edu.year, 9);
      page.drawText(edu.year, { x: A4_W - margin - yearW, y, size: 9, font: userFont });
      y -= 18;
    }
  }

  if (data.skills.length > 0) {
    addSection('Skills');
    drawWrappedText(data.skills.join('  •  '), margin, 10, userFont, 15);
  }

  const bytes = await pdfDoc.save();
  return {
    blob: new Blob([new Uint8Array(bytes)], { type: 'application/pdf' }),
    name: `${data.fullName.replace(/\s+/g, '_')}_Resume.pdf`,
  };
}

// ─── FEATURE 5: SMART WATERMARK ───────────────────────────────────────
export interface WatermarkConfig {
  text?: string;
  logoDataUrl?: string;
  opacity: number;
  rotation: number;
  position: 'center' | 'top-left' | 'top-right' | 'bottom-left' | 'bottom-right' | 'tile';
  fontSize?: number;
  color?: string;
  pages?: 'all' | 'first' | 'custom';
  customPages?: number[];
}

export async function applySmartWatermark(
  file: File,
  config: WatermarkConfig
): Promise<{ blob: Blob; name: string }> {
  const buffer = await file.arrayBuffer();
  const pdfDoc = await PDFDocument.load(buffer);
  const fallbackFont = await pdfDoc.embedFont(StandardFonts.Helvetica);
  const allPages = pdfDoc.getPages();
  const fontSize = config.fontSize || 48;
  const opacity = config.opacity ?? 0.2;
  const rotation = config.rotation ?? 45;

  let watermarkFont = fallbackFont;
  if (config.text && needsUnicodeFont(config.text)) {
    watermarkFont = await getUnicodeFontForPdfLib(config.text, pdfDoc);
  }

  let targetIndices: number[];
  if (config.pages === 'first') targetIndices = [0];
  else if (config.pages === 'custom' && config.customPages) targetIndices = config.customPages.map(p => Math.min(p, allPages.length - 1));
  else targetIndices = allPages.map((_, i) => i);

  let logoImage: PDFImage | null = null;
  if (config.logoDataUrl) {
    const raw = config.logoDataUrl.split(',')[1];
    const imgBytes = Uint8Array.from(atob(raw), c => c.charCodeAt(0));
    try {
      logoImage = await pdfDoc.embedPng(imgBytes);
    } catch {
      try { logoImage = await pdfDoc.embedJpg(imgBytes); } catch {}
    }
  }

  const hexToRgb = (hex: string) => {
    const result = /^#?([a-f\d]{2})([a-f\d]{2})([a-f\d]{2})$/i.exec(hex);
    return result ? { r: parseInt(result[1], 16) / 255, g: parseInt(result[2], 16) / 255, b: parseInt(result[3], 16) / 255 } : { r: 0.3, g: 0.3, b: 0.3 };
  };
  const textColor = config.color ? hexToRgb(config.color) : { r: 0.3, g: 0.3, b: 0.3 };

  for (const idx of targetIndices) {
    const page = allPages[idx];
    const { width, height } = page.getSize();

    const positions: { x: number; y: number }[] = [];
    if (config.position === 'tile') {
      for (let tx = 0; tx < width; tx += 200) {
        for (let ty = 0; ty < height; ty += 200) {
          positions.push({ x: tx + 50, y: ty + 50 });
        }
      }
    } else {
      let x = width / 3;
      let y = height / 2;
      if (config.position === 'top-left') { x = 30; y = height - 60; }
      else if (config.position === 'top-right') { x = width - 200; y = height - 60; }
      else if (config.position === 'bottom-left') { x = 30; y = 60; }
      else if (config.position === 'bottom-right') { x = width - 200; y = 60; }
      positions.push({ x, y });
    }

    for (const pos of positions) {
      if (config.text) {
        let drawText = config.text;
        if (needsRTLReordering(config.text)) {
          drawText = processForPdfRendering(config.text);
        }
        page.drawText(drawText, {
          x: pos.x, y: pos.y, size: fontSize,
          font: watermarkFont,
          color: rgb(textColor.r, textColor.g, textColor.b),
          opacity, rotate: degrees(rotation),
        });
      }
      if (logoImage) {
        const logoW = 60;
        const logoH = (logoImage.height / logoImage.width) * logoW;
        page.drawImage(logoImage, {
          x: pos.x, y: pos.y - logoH,
          width: logoW, height: logoH,
          opacity,
        });
      }
    }
  }

  const bytes = await pdfDoc.save({ useObjectStreams: true });
  return {
    blob: new Blob([new Uint8Array(bytes)], { type: 'application/pdf' }),
    name: `watermarked_${file.name}`,
  };
}

// ─── FEATURE 6: PDF TEMPLATE LIBRARY ──────────────────────────────────
export interface Template {
  id: string;
  name: string;
  description: string;
  category: 'resume' | 'invoice' | 'agreement' | 'certificate' | 'letter';
  content: Record<string, any>;
  previewUrl?: string;
  createdAt: string;
  updatedAt: string;
}

const TEMPLATES_KEY = 'pdf_templates';

export function getTemplates(): Template[] {
  if (typeof window === 'undefined') return [];
  const raw = localStorage.getItem(TEMPLATES_KEY);
  if (raw) {
    try { return JSON.parse(raw); } catch {}
  }
  return [];
}

export function saveTemplates(templates: Template[]): void {
  if (typeof window === 'undefined') return;
  localStorage.setItem(TEMPLATES_KEY, JSON.stringify(templates));
}

export function addTemplate(template: Template): void {
  const templates = getTemplates();
  templates.push(template);
  saveTemplates(templates);
}

export function deleteTemplate(id: string): void {
  const templates = getTemplates().filter(t => t.id !== id);
  saveTemplates(templates);
}

export function updateTemplate(id: string, updates: Partial<Template>): void {
  const templates = getTemplates().map(t => t.id === id ? { ...t, ...updates, updatedAt: new Date().toISOString() } : t);
  saveTemplates(templates);
}

export async function generateTemplatePDF(template: Template): Promise<{ blob: Blob; name: string }> {
  const pdfDoc = await PDFDocument.create();
  const A4_W = 595.28;
  const A4_H = 841.89;
  const margin = 57;
  const maxW = A4_W - 2 * margin;

  const allContent = JSON.stringify(template.content);
  const fonts = await getUnicodeFontPairPdfLib(template.name + allContent, pdfDoc);
  const userFont = fonts.regular;
  const boldFont = fonts.bold;

  let page = pdfDoc.addPage([A4_W, A4_H]);
  let y = A4_H - margin;

  const addPage = () => { page = pdfDoc.addPage([A4_W, A4_H]); y = A4_H - margin; };

  page.drawText(template.name, { x: margin, y, size: 22, font: boldFont });
  y -= 24;

  const renderContent = (obj: Record<string, any>, indent = 0) => {
    const indentStr = '  '.repeat(indent);
    for (const [key, value] of Object.entries(obj)) {
      if (y < 60) addPage();
      if (typeof value === 'object' && value !== null) {
        const header = `${indentStr}${key}:`;
        const headerW = boldFont.widthOfTextAtSize(header, 10);
        page.drawText(header, { x: margin + indent * 12, y, size: 10, font: boldFont });
        y -= 14;
        renderContent(value, indent + 1);
      } else {
        const prefix = indent > 0 ? indentStr : '';
        const text = `${prefix}${key}: ${value}`;
        const lines = wrapText(text, maxW, 10, userFont);
        for (const line of lines) {
          if (y < 40) addPage();
          page.drawText(line, { x: margin + indent * 12, y, size: 10, font: userFont });
          y -= 13;
        }
        y -= 4;
      }
    }
  };

  renderContent(template.content);

  const bytes = await pdfDoc.save();
  return { blob: new Blob([new Uint8Array(bytes)], { type: 'application/pdf' }), name: `${template.name.replace(/\s+/g, '_')}.pdf` };
}

// ─── FEATURE 7: COMMUNITY Q&A ────────────────────────────────────────
export interface QAUser {
  id: string;
  name: string;
  avatar: string;
}

export interface QAQuestion {
  id: string;
  title: string;
  body: string;
  tags: string[];
  category: string;
  author: QAUser;
  votes: number;
  answers: QAAnswer[];
  bestAnswerId: string | null;
  createdAt: string;
  viewCount: number;
  reports: string[];
}

export interface QAAnswer {
  id: string;
  body: string;
  author: QAUser;
  votes: number;
  isBestAnswer: boolean;
  createdAt: string;
  reports: string[];
}

const QA_KEY = 'qa_questions';

export function getQAQuestions(): QAQuestion[] {
  if (typeof window === 'undefined') return [];
  const raw = localStorage.getItem(QA_KEY);
  if (raw) {
    try { return JSON.parse(raw); } catch {}
  }
  const sample: QAQuestion[] = [
    {
      id: '1', title: 'How to merge multiple PDFs?', body: 'I have several PDF files I need to combine into one document. What is the best approach?', tags: ['merge', 'beginner'], category: 'General', author: { id: 'u1', name: 'User1', avatar: '' }, votes: 5, answers: [
        { id: 'a1', body: 'Use the Merge PDF tool on this site. Upload your files and click execute.', author: { id: 'u2', name: 'Helper', avatar: '' }, votes: 3, isBestAnswer: true, createdAt: new Date().toISOString(), reports: [] }
      ], bestAnswerId: 'a1', createdAt: new Date().toISOString(), viewCount: 42, reports: []
    },
    {
      id: '2', title: 'PDF compression not reducing size', body: 'I tried compressing my PDF but the file size barely changed. Any tips?', tags: ['compress', 'help'], category: 'Technical', author: { id: 'u3', name: 'Curious', avatar: '' }, votes: 3, answers: [], bestAnswerId: null, createdAt: new Date().toISOString(), viewCount: 18, reports: []
    }
  ];
  saveQAQuestions(sample);
  return sample;
}

export function saveQAQuestions(questions: QAQuestion[]): void {
  if (typeof window === 'undefined') return;
  localStorage.setItem(QA_KEY, JSON.stringify(questions));
}

export function addQAQuestion(question: QAQuestion): void {
  const questions = getQAQuestions();
  questions.unshift(question);
  saveQAQuestions(questions);
}

export function addQAAnswer(questionId: string, answer: QAAnswer): void {
  const questions = getQAQuestions();
  const q = questions.find(q => q.id === questionId);
  if (q) {
    q.answers.push(answer);
    saveQAQuestions(questions);
  }
}

export function voteQAQuestion(questionId: string, delta: 1 | -1): void {
  const questions = getQAQuestions();
  const q = questions.find(q => q.id === questionId);
  if (q) { q.votes += delta; saveQAQuestions(questions); }
}

export function voteQAAnswer(questionId: string, answerId: string, delta: 1 | -1): void {
  const questions = getQAQuestions();
  const q = questions.find(q => q.id === questionId);
  if (q) {
    const a = q.answers.find(a => a.id === answerId);
    if (a) { a.votes += delta; saveQAQuestions(questions); }
  }
}

export function markBestAnswer(questionId: string, answerId: string): void {
  const questions = getQAQuestions();
  const q = questions.find(q => q.id === questionId);
  if (q) {
    q.answers.forEach(a => a.isBestAnswer = a.id === answerId);
    q.bestAnswerId = answerId;
    saveQAQuestions(questions);
  }
}

export function reportQAQuestion(questionId: string, userId: string): void {
  const questions = getQAQuestions();
  const q = questions.find(q => q.id === questionId);
  if (q && !q.reports.includes(userId)) { q.reports.push(userId); saveQAQuestions(questions); }
}

export function reportQAAnswer(questionId: string, answerId: string, userId: string): void {
  const questions = getQAQuestions();
  const q = questions.find(q => q.id === questionId);
  if (q) {
    const a = q.answers.find(a => a.id === answerId);
    if (a && !a.reports.includes(userId)) { a.reports.push(userId); saveQAQuestions(questions); }
  }
}

export function getQACategories(): string[] {
  return ['General', 'Technical', 'Feature Request', 'Bug Report', 'Tutorial', 'Other'];
}
