export const toolFAQs: Record<string, Array<{ question: string; answer: string }>> = {
  merge: [
    { question: 'How do I merge PDF files online?', answer: 'Upload your PDF files, arrange them in the desired order using drag-and-drop, and click "Merge PDF". Your combined document will be ready to download instantly.' },
    { question: 'Is there a file size limit for merging PDFs?', answer: 'DocuPDF supports large PDF files. Since processing happens entirely in your browser, the practical limit depends on your device memory. Most users can merge files totaling hundreds of megabytes.' },
    { question: 'Are my files secure when merging?', answer: 'Yes. All PDF processing happens locally in your browser using client-side JavaScript. Your files are never uploaded to any server, ensuring complete privacy.' },
    { question: 'Can I merge more than two PDF files at once?', answer: 'Yes, you can upload as many PDF files as you need. Simply drag and drop all the files you want to combine, arrange them in your preferred order, and merge them into a single document.' },
    { question: 'Will merging PDFs affect the quality of my documents?', answer: 'No. DocuPDF preserves the original quality of all pages during merging. Text, images, fonts, and layouts remain exactly as they appear in the source files.' },
  ],
  split: [
    { question: 'How do I split a PDF into separate files?', answer: 'Upload your PDF, select the pages you want to extract by clicking on their thumbnails, and click "Split PDF". You can extract individual pages or page ranges.' },
    { question: 'Can I extract specific pages from a PDF?', answer: 'Yes. After uploading your PDF, click on individual page thumbnails to select them. You can also select page ranges for batch extraction.' },
    { question: 'Is there a limit on how many pages I can extract?', answer: 'No, you can extract any number of pages from your PDF. Select one page or all pages — the tool handles documents of any size.' },
    { question: 'Does splitting a PDF reduce its quality?', answer: 'No. Splitting simply separates pages without re-encoding or modifying content. Each extracted page retains its original quality, resolution, and formatting.' },
  ],
  compress: [
    { question: 'How much can I reduce PDF file size?', answer: 'Compression results vary depending on the content. Text-heavy PDFs can often be reduced by 50-80%, while image-heavy documents may see 20-50% reduction while maintaining quality.' },
    { question: 'Does compression reduce PDF quality?', answer: 'DocuPDF uses intelligent compression that optimizes file size while preserving maximum visual quality. The compression is lossless for most document types.' },
    { question: 'Why should I compress a PDF?', answer: 'Compressed PDFs load faster, are easier to email, consume less storage space, and improve website performance. Many email providers have attachment size limits that compressed PDFs can easily meet.' },
    { question: 'Can I compress a PDF with images and graphics?', answer: 'Yes. DocuPDF intelligently optimizes embedded images, fonts, and other resources within the PDF to reduce file size while keeping visual quality high.' },
  ],
  rotate: [
    { question: 'How do I rotate PDF pages?', answer: 'Upload your PDF file, hover over individual pages to rotate them left or right, or use the "Rotate All" buttons to rotate every page at once. Click "Save" to download.' },
    { question: 'Can I rotate individual pages differently?', answer: 'Yes. You can rotate each page independently. For example, rotate page 1 by 90 degrees clockwise and page 3 by 180 degrees — each page can have its own rotation.' },
    { question: 'What rotation angles are supported?', answer: 'DocuPDF supports 90, 180, and 270 degree rotations in both clockwise and counterclockwise directions. You can apply any combination of rotations to any page.' },
    { question: 'Will rotating affect the PDF quality?', answer: 'No. Rotating PDF pages only changes the orientation angle. All content, text, images, and formatting remain exactly the same with zero quality loss.' },
  ],
  'pdf-to-word': [
    { question: 'How do I convert PDF to Word?', answer: 'Upload your PDF file, and DocuPDF will convert it to an editable DOCX document. The conversion preserves text, formatting, images, and layout.' },
    { question: 'Is the converted Word file editable?', answer: 'Yes. The converted DOCX file is fully editable in Microsoft Word, Google Docs, or any compatible word processor. All text and formatting are preserved.' },
    { question: 'Does PDF to Word conversion preserve formatting?', answer: 'Yes. Our converter maintains fonts, colors, tables, images, and page layout from the original PDF so your Word document looks as close to the original as possible.' },
    { question: 'Can I convert a scanned PDF to Word?', answer: 'For scanned PDFs, use our OCR tool first to make the text selectable, then convert the resulting PDF to Word for best results.' },
  ],
  'word-to-pdf': [
    { question: 'How do I convert Word to PDF?', answer: 'Upload your DOC or DOCX file, and DocuPDF will convert it to a PDF document while preserving all formatting, fonts, and layout.' },
    { question: 'Does the PDF preserve Word formatting?', answer: 'Yes. Our converter maintains fonts, colors, images, tables, and page layout from your original Word document.' },
    { question: 'Can I convert Word documents with images to PDF?', answer: 'Yes. Images, charts, and embedded objects in your Word document are preserved in the resulting PDF output.' },
    { question: 'Is the Word to PDF conversion free?', answer: 'Yes, DocuPDF offers completely free Word to PDF conversion with no file size limits, no watermarks, and no registration required.' },
  ],
  'jpg-to-pdf': [
    { question: 'How do I convert JPG to PDF?', answer: 'Upload your JPG, PNG, or other image files, adjust orientation and margins if needed, and click "Convert to PDF". Your images will be combined into a single PDF document.' },
    { question: 'Can I convert multiple images to one PDF?', answer: 'Yes. Upload multiple images and they will be combined into a single PDF, with one image per page. You can adjust the order and orientation.' },
    { question: 'What image formats are supported?', answer: 'DocuPDF supports JPG, JPEG, PNG, BMP, GIF, and TIFF image formats for conversion to PDF.' },
    { question: 'Will the image quality change after conversion?', answer: 'No. Your images are embedded in the PDF at their original resolution and quality. No compression or resizing is applied.' },
  ],
  'pdf-to-jpg': [
    { question: 'How do I convert PDF to JPG?', answer: 'Upload your PDF file and DocuPDF will extract each page as a high-quality JPG image. You can download individual pages or all pages at once.' },
    { question: 'What is the image quality of the converted JPGs?', answer: 'DocuPDF extracts pages at their original resolution, producing crisp and clear JPG images suitable for printing or sharing.' },
    { question: 'Can I convert specific pages to JPG?', answer: 'Yes. You can select individual pages to convert rather than extracting the entire document as images.' },
    { question: 'Is PDF to JPG conversion free?', answer: 'Yes. DocuPDF offers free PDF to JPG conversion with no limits on the number of pages or files you can convert.' },
  ],
  'excel-to-pdf': [
    { question: 'How do I convert Excel to PDF?', answer: 'Upload your XLS or XLSX file and DocuPDF will convert it to a PDF document that preserves your spreadsheet layout, tables, charts, and formatting.' },
    { question: 'Will my Excel formulas be preserved?', answer: 'The PDF output shows the calculated values of your formulas. The visual layout and cell formatting are preserved exactly as they appear in Excel.' },
    { question: 'Can I convert multiple Excel sheets to PDF?', answer: 'Yes. All worksheets in your Excel file will be included in the resulting PDF document, with each sheet properly laid out.' },
    { question: 'Does the conversion support charts and graphs?', answer: 'Yes. Charts, graphs, images, and other visual elements embedded in your Excel spreadsheet are preserved in the PDF output.' },
  ],
  'ppt-to-pdf': [
    { question: 'How do I convert PowerPoint to PDF?', answer: 'Upload your PPT or PPTX file and DocuPDF will convert each slide into a PDF page while preserving the layout, images, and formatting.' },
    { question: 'Will slide animations be preserved?', answer: 'Animations and transitions are not preserved in PDF format, but all static content including text, images, charts, and layout are maintained perfectly.' },
    { question: 'Can I convert large PowerPoint presentations?', answer: 'Yes. DocuPDF handles presentations of any size. Processing happens in your browser so there are no server-side file size limits.' },
    { question: 'Is PowerPoint to PDF conversion free?', answer: 'Yes. Convert unlimited PowerPoint presentations to PDF for free. No account or registration needed.' },
  ],
  'html-to-pdf': [
    { question: 'How do I convert HTML to PDF?', answer: 'Paste a URL or HTML code directly into the tool, and DocuPDF will render it as a perfectly formatted PDF document.' },
    { question: 'Can I convert a webpage to PDF?', answer: 'Yes. Simply paste the URL of any webpage and DocuPDF will capture the full page content and convert it to a PDF.' },
    { question: 'Does it support CSS styling?', answer: 'Yes. The HTML to PDF converter renders CSS, JavaScript, and modern web layouts to produce pixel-perfect PDF output.' },
    { question: 'Can I convert HTML code snippets to PDF?', answer: 'Yes. Paste your HTML code directly and it will be rendered and converted to a downloadable PDF document.' },
  ],
  'pdf-to-excel': [
    { question: 'How do I convert PDF to Excel?', answer: 'Upload your PDF file and DocuPDF will extract tables and text data into an editable Excel spreadsheet format.' },
    { question: 'Can the tool extract tables from PDF?', answer: 'Yes. DocuPDF detects and extracts tabular data from PDF documents, preserving column structure and cell values in Excel format.' },
    { question: 'Is the extracted Excel data editable?', answer: 'Yes. The output is a fully editable XLSX file that you can modify, sort, filter, and analyze in Excel or Google Sheets.' },
    { question: 'Does PDF to Excel conversion work with scanned documents?', answer: 'For scanned PDFs, the OCR feature helps recognize text before extraction, improving the accuracy of the Excel output.' },
  ],
  'pdf-to-ppt': [
    { question: 'How do I convert PDF to PowerPoint?', answer: 'Upload your PDF and DocuPDF will convert each page into an editable PowerPoint slide while preserving the layout and images.' },
    { question: 'Can I edit the converted PowerPoint slides?', answer: 'Yes. The resulting PPTX file is fully editable. You can modify text, add animations, and make any changes in PowerPoint.' },
    { question: 'Will the layout be preserved?', answer: 'Yes. Each PDF page becomes a PowerPoint slide with the original layout, fonts, images, and visual elements maintained.' },
    { question: 'Is PDF to PowerPoint conversion free?', answer: 'Yes. Convert unlimited PDF files to PowerPoint for free with no registration or account required.' },
  ],
  'pdf-to-pdfa': [
    { question: 'What is PDF/A format?', answer: 'PDF/A is an ISO-standardized version of PDF designed for long-term archiving. It ensures documents can be opened and displayed the same way years into the future.' },
    { question: 'Why should I convert PDF to PDF/A?', answer: 'PDF/A is required for legal compliance, government submissions, and archival purposes. It embeds fonts and removes external dependencies to ensure consistent rendering.' },
    { question: 'Is the conversion to PDF/A compliant?', answer: 'Yes. DocuPDF converts your PDF to PDF/A format following the ISO 19005 standard for reliable long-term document preservation.' },
    { question: 'Will the PDF/A file look different?', answer: 'The visual appearance remains the same. PDF/A only changes the internal structure to ensure long-term compatibility without affecting how the document looks.' },
  ],
  'pdf-to-markdown': [
    { question: 'How do I convert PDF to Markdown?', answer: 'Upload your PDF and DocuPDF will extract the text, headings, and structure into clean Markdown format suitable for developers and documentation.' },
    { question: 'What Markdown features are preserved?', answer: 'Headings, lists, bold/italic text, links, and basic table structures are preserved in the Markdown output.' },
    { question: 'Is this useful for developers?', answer: 'Yes. Markdown output is ideal for README files, documentation, wikis, and any text-based workflow where Markdown is preferred.' },
    { question: 'Does it support multi-column PDFs?', answer: 'DocuPDF intelligently detects content flow in multi-column layouts and produces clean, readable Markdown output.' },
  ],
  'pdf-translator': [
    { question: 'How does the AI PDF translator work?', answer: 'Upload your PDF and select the target language. Our AI analyzes the document content and translates all text while preserving the original layout and formatting.' },
    { question: 'How many languages are supported?', answer: 'DocuPDF supports translation into over 50 languages including Spanish, French, German, Chinese, Arabic, Hindi, Portuguese, and many more.' },
    { question: 'Will the layout be preserved after translation?', answer: 'Yes. The AI translator maintains the original document layout, images, tables, and formatting while translating all text content.' },
    { question: 'Is the PDF translation accurate?', answer: 'Our AI-powered translation provides high-quality, natural-sounding translations. For technical documents, we recommend reviewing the output for domain-specific terminology.' },
  ],
  watermark: [
    { question: 'How do I add a watermark to a PDF?', answer: 'Upload your PDF, enter your watermark text, customize the font, size, color, and position, then click "Add Watermark" to download the watermarked document.' },
    { question: 'Can I add image watermarks to PDF?', answer: 'Yes. DocuPDF supports both text and image watermarks. You can upload your logo or image and place it anywhere on the PDF pages.' },
    { question: 'Can I adjust the watermark opacity?', answer: 'Yes. You can control the transparency of your watermark from fully opaque to very subtle, ensuring it does not obscure the document content.' },
    { question: 'Will the watermark appear on all pages?', answer: 'By default, watermarks are applied to all pages. You can also choose specific pages to watermark depending on your needs.' },
  ],
  'smart-watermark': [
    { question: 'What is the difference between regular and smart watermark?', answer: 'Smart Watermark offers advanced features like batch processing, precise positioning with coordinates, custom rotation angles, and opacity control for professional watermarking.' },
    { question: 'Can I watermark multiple PDFs at once?', answer: 'Yes. Smart Watermark supports batch processing, allowing you to apply the same watermark to multiple PDF files simultaneously.' },
    { question: 'How precise is the watermark positioning?', answer: 'You can set exact X and Y coordinates, rotation angle, and opacity level for pixel-perfect watermark placement on every page.' },
    { question: 'Can I watermark only specific pages?', answer: 'Yes. Smart Watermark lets you choose specific page ranges or apply watermarks to all pages in your document.' },
  ],
  protect: [
    { question: 'How do I password-protect a PDF?', answer: 'Upload your PDF, enter a strong password, and click "Protect PDF". Your document will be encrypted with 256-bit AES encryption.' },
    { question: 'What encryption is used for PDF protection?', answer: 'DocuPDF uses 256-bit AES encryption, the same standard used by banks and government agencies for securing sensitive documents.' },
    { question: 'Can I set different permissions for printing and editing?', answer: 'Yes. You can control what recipients can do with your protected PDF, including restricting printing, copying, and editing while allowing viewing.' },
    { question: 'Is password-protected PDF safe?', answer: 'Yes. 256-bit AES encryption is virtually unbreakable with current technology. Your PDF content remains secure against unauthorized access.' },
  ],
  unlock: [
    { question: 'How do I unlock a PDF?', answer: 'Upload your password-protected PDF, enter the correct password, and click "Unlock PDF". The password restriction will be removed from your document.' },
    { question: 'Do I need the password to unlock a PDF?', answer: 'Yes. You must know the current password to remove PDF restrictions. DocuPDF cannot bypass passwords — it simply removes the restriction once you provide the password.' },
    { question: 'Will unlocking change my PDF content?', answer: 'No. Unlocking only removes the password protection. All content, formatting, images, and layout remain exactly the same.' },
    { question: 'Is the unlock process secure?', answer: 'Yes. All processing happens locally in your browser. Your PDF and password are never sent to any server.' },
  ],
  'password-check': [
    { question: 'What does the PDF password checker do?', answer: 'It analyzes your PDF password strength, estimates crack time, and provides recommendations to create stronger passwords for better security.' },
    { question: 'Is my password sent to a server?', answer: 'No. All password analysis happens locally in your browser. Your password is never transmitted anywhere.' },
    { question: 'How accurate is the crack time estimate?', answer: 'The estimate is based on password entropy, character set, and current computing capabilities. It provides a realistic assessment of password strength.' },
    { question: 'Can I check passwords for any PDF?', answer: 'Yes. You can analyze any PDF password, whether it is owner or user password, to understand how secure it is.' },
  ],
  organize: [
    { question: 'How do I reorder PDF pages?', answer: 'Upload your PDF, then drag and drop page thumbnails to rearrange them in any order. Click "Save" when you are satisfied with the arrangement.' },
    { question: 'Can I add pages from another PDF?', answer: 'Yes. You can upload multiple PDFs and mix their pages together, reordering them as needed before saving the final document.' },
    { question: 'Can I delete pages while organizing?', answer: 'Yes. Click the delete button on any page thumbnail to remove it from the document before saving.' },
    { question: 'Is there a visual preview of pages?', answer: 'Yes. All pages are displayed as thumbnails so you can visually identify and rearrange them easily.' },
  ],
  crop: [
    { question: 'How do I crop a PDF page?', answer: 'Upload your PDF, select a page, then drag the crop handles to define the area you want to keep. Click "Apply Crop" to save.' },
    { question: 'Can I crop all pages at once?', answer: 'Yes. Apply crop settings to all pages simultaneously for consistent margins throughout your document.' },
    { question: 'What page sizes can I crop to?', answer: 'You can crop to custom dimensions or choose from standard sizes like A4, Letter, Legal, and more.' },
    { question: 'Will cropping remove content permanently?', answer: 'Cropping hides the content outside the selected area. The hidden content is removed from view in the output PDF.' },
  ],
  compare: [
    { question: 'How does the PDF comparison tool work?', answer: 'Upload two PDF documents and DocuPDF will display them side-by-side, highlighting differences in text, formatting, and layout between the two versions.' },
    { question: 'What types of changes are detected?', answer: 'The tool detects text additions, deletions, and modifications. It also highlights formatting changes, layout shifts, and image differences.' },
    { question: 'Can I compare PDFs of different lengths?', answer: 'Yes. The comparison tool handles PDFs with different numbers of pages and identifies content differences across all pages.' },
    { question: 'Is the comparison accurate?', answer: 'DocuPDF uses advanced diff algorithms to provide accurate, detailed comparisons. Each change is clearly highlighted for easy review.' },
  ],
  ocr: [
    { question: 'What is OCR for PDF?', answer: 'OCR (Optical Character Recognition) converts scanned documents and image-based PDFs into searchable, selectable text that you can copy and search.' },
    { question: 'How accurate is the OCR?', answer: 'DocuPDF uses Tesseract.js OCR engine which provides high accuracy for clear, well-scanned documents. Accuracy may vary with handwritten or low-quality scans.' },
    { question: 'What languages does OCR support?', answer: 'The OCR engine supports multiple languages including English, Spanish, French, German, Chinese, Japanese, Arabic, and many more.' },
    { question: 'Will OCR change my PDF appearance?', answer: 'No. OCR adds a text layer behind the original images, making text selectable without changing how the document looks.' },
  ],
  'ocr-editable': [
    { question: 'How is OCR to Editable PDF different from regular OCR?', answer: 'OCR to Editable PDF creates a fully editable document where you can modify text directly, not just search and copy. It reconstructs the PDF with editable text elements.' },
    { question: 'Can I edit the text after OCR conversion?', answer: 'Yes. The output PDF contains editable text layers that allow you to modify, add, or delete text just like a regular document.' },
    { question: 'Is the editable output accurate?', answer: 'The tool preserves the original layout while making text editable. For best results, use high-quality scans with clear, printed text.' },
    { question: 'What file types can be converted?', answer: 'Any scanned PDF or image-based document can be converted to an editable PDF using the OCR-to-editable feature.' },
  ],
  repair: [
    { question: 'How does the PDF repair tool work?', answer: 'Upload your corrupted PDF and DocuPDF will analyze the file structure, recover readable data, and generate a new, functional PDF document.' },
    { question: 'What types of PDF damage can be fixed?', answer: 'The tool can fix corrupted headers, broken cross-reference tables, invalid object references, and other structural issues that prevent PDFs from opening.' },
    { question: 'Will repair recover all my content?', answer: 'In most cases, yes. The repair tool extracts all recoverable text, images, and formatting from the corrupted file and rebuilds a working PDF.' },
    { question: 'Is the repair process safe?', answer: 'Yes. The original corrupted file is not modified. A new repaired PDF is generated, keeping your source file intact.' },
  ],
  'scan-to-pdf': [
    { question: 'How do I scan documents to PDF?', answer: 'Use your device camera to capture a document, apply auto-crop and enhancement, and convert the scan directly to a PDF file.' },
    { question: 'Does the scan support auto-crop?', answer: 'Yes. The scanner automatically detects document edges and crops the image to remove background and improve readability.' },
    { question: 'Can I enhance scanned images?', answer: 'Yes. Auto-enhancement improves contrast, brightness, and sharpness to make scanned documents clearer and more readable.' },
    { question: 'Is mobile scanning supported?', answer: 'Yes. DocuPDF works on any device with a camera, including smartphones, tablets, and laptops.' },
  ],
  'pdf-forms': [
    { question: 'Can I create fillable PDF forms?', answer: 'Yes. DocuPDF lets you create fillable PDF forms with text fields, checkboxes, dropdowns, and signature fields that others can fill out.' },
    { question: 'How do I fill out a PDF form?', answer: 'Upload your PDF form, click on each field to enter your information, and download the completed form when finished.' },
    { question: 'Are fillable forms compatible with Adobe Reader?', answer: 'Yes. Fillable forms created with DocuPDF are standard PDF forms compatible with Adobe Acrobat, Preview, and other PDF readers.' },
    { question: 'Can I add signature fields to forms?', answer: 'Yes. You can include signature fields in your forms that recipients can sign digitally using any PDF reader.' },
  ],
  redact: [
    { question: 'How do I redact sensitive information from a PDF?', answer: 'Upload your PDF, select the areas containing sensitive information, and click "Redact". The selected content will be permanently removed from the document.' },
    { question: 'Is redaction permanent?', answer: 'Yes. Redacted content is permanently removed from the PDF, not just hidden. The data cannot be recovered from the redacted document.' },
    { question: 'Can I redact text by searching?', answer: 'Yes. You can search for specific words or phrases and redact all occurrences throughout the document.' },
    { question: 'Does redaction affect the layout?', answer: 'Redacted areas are covered with black bars. The surrounding content and layout remain unchanged.' },
  ],
  esignature: [
    { question: 'How do I sign a PDF electronically?', answer: 'Upload your PDF, draw or type your signature, position it where needed on the document, and download the signed PDF.' },
    { question: 'Are electronic signatures legally valid?', answer: 'Electronic signatures are legally recognized in most countries under eSignature laws like ESIGN Act (US), eIDAS (EU), and similar legislation worldwide.' },
    { question: 'Can I save my signature for reuse?', answer: 'Yes. You can create and save your signature in the browser for quick signing of future documents.' },
    { question: 'Can I request signatures from others?', answer: 'Yes. DocuPDF supports signature request workflows where you can send documents to others for electronic signing.' },
  ],
  'page-numbers': [
    { question: 'How do I add page numbers to a PDF?', answer: 'Upload your PDF, choose the position (top, bottom, center, corners), select font style and size, and click "Add Page Numbers".' },
    { question: 'Can I use Roman numerals for page numbers?', answer: 'Yes. DocuPDF supports Arabic numerals (1, 2, 3), Roman numerals (I, II, III), and other numbering formats.' },
    { question: 'Where can page numbers be placed?', answer: 'Page numbers can be placed at the top-left, top-center, top-right, bottom-left, bottom-center, or bottom-right of each page.' },
    { question: 'Can I customize the page number font?', answer: 'Yes. You can choose font family, size, and color to match your document style.' },
  ],
  'delete-pages': [
    { question: 'How do I delete pages from a PDF?', answer: 'Upload your PDF, select the pages you want to remove by clicking their thumbnails, and click "Delete Pages".' },
    { question: 'Can I delete multiple pages at once?', answer: 'Yes. Select multiple pages by clicking their thumbnails and delete them all in one action.' },
    { question: 'Is there a way to preview before deleting?', answer: 'Yes. All pages are shown as thumbnails so you can visually confirm which pages to remove before proceeding.' },
    { question: 'Can I undo page deletion?', answer: 'The deletion is only applied when you click the save button. You can re-select pages before saving to restore any accidentally deselected pages.' },
  ],
  summarizer: [
    { question: 'How does the AI PDF summarizer work?', answer: 'Upload your PDF and our AI (powered by Google Gemini) analyzes the document content to generate comprehensive summaries, key takeaways, or study questions.' },
    { question: 'Is there a page limit for PDF summarization?', answer: 'The AI summarizer works best with documents up to 30 pages. For longer documents, we recommend splitting them first.' },
    { question: 'What types of summaries can it generate?', answer: 'DocuPDF can produce brief summaries, detailed overviews, bullet-point key takeaways, and even study questions based on your PDF content.' },
    { question: 'What languages does the summarizer support?', answer: 'The AI summarizer can summarize PDFs in multiple languages including English, Spanish, French, German, and many more.' },
  ],
  translate: [
    { question: 'How do I translate a PDF?', answer: 'Upload your PDF, select the target language, and click "Translate". The AI will translate all text content while preserving the document layout.' },
    { question: 'How many languages can I translate to?', answer: 'DocuPDF supports translation into over 50 languages including major world languages like Spanish, French, Chinese, Arabic, Hindi, and more.' },
    { question: 'Will the layout be preserved after translation?', answer: 'Yes. The translator maintains the original layout, images, tables, and formatting while translating text content.' },
    { question: 'Can I translate technical or legal documents?', answer: 'Yes. The AI handles technical and legal terminology well. We recommend reviewing specialized documents for domain-specific accuracy.' },
  ],
  'resume-builder': [
    { question: 'How do I build a resume online?', answer: 'Choose a template, fill in your personal information, work experience, education, and skills. The live preview shows your resume as you build it. Export as PDF when ready.' },
    { question: 'Are the resume templates free?', answer: 'Yes. DocuPDF offers a collection of professional, modern resume templates at no cost. All templates are fully customizable.' },
    { question: 'Can I export my resume as PDF?', answer: 'Yes. Your completed resume can be exported as a high-quality PDF document ready for printing or digital submission.' },
    { question: 'Can I customize the template colors and fonts?', answer: 'Yes. Each template supports custom colors, fonts, and section arrangements to match your personal style.' },
  ],
  workflows: [
    { question: 'What are PDF workflows?', answer: 'PDF workflows let you chain multiple PDF operations together into a single automated process, saving time on repetitive tasks.' },
    { question: 'Can I create custom workflows?', answer: 'Yes. Build custom workflows by combining tools like merge, compress, watermark, and protect into a single processing pipeline.' },
    { question: 'Can I save and reuse workflows?', answer: 'Yes. Create a workflow once and save it for repeated use. This is ideal for batch processing similar documents.' },
    { question: 'How many tools can I chain together?', answer: 'There is no limit. You can chain as many tools as needed in a single workflow for complex document processing.' },
  ],
  templates: [
    { question: 'What types of PDF templates are available?', answer: 'DocuPDF offers templates for resumes, invoices, agreements, letters, reports, and more. All templates are professionally designed and customizable.' },
    { question: 'Are the templates free to download?', answer: 'Yes. All PDF templates in the collection are completely free to download and use for personal or professional purposes.' },
    { question: 'Can I customize the templates?', answer: 'Yes. Templates can be customized with your own text, images, and branding before downloading as a PDF.' },
    { question: 'What file format are the templates in?', answer: 'Templates are available as editable PDF files that you can fill out directly in your browser.' },
  ],
};

export const toolFeatures: Record<string, { icon: string; title: string; description: string }[]> = {
  merge: [
    { icon: 'FilePlus', title: 'Unlimited Files', description: 'Merge as many PDFs as you need with no file count limits' },
    { icon: 'Shield', title: '100% Private', description: 'All processing happens in your browser — files never leave your device' },
    { icon: 'ArrowUpDown', title: 'Drag & Drop Order', description: 'Reorder pages by dragging thumbnails into the exact sequence you want' },
    { icon: 'Zap', title: 'Instant Results', description: 'Get your merged PDF in seconds with no quality loss' },
  ],
  split: [
    { icon: 'Scissors', title: 'Extract Pages', description: 'Pull out specific pages or ranges from any PDF document' },
    { icon: 'Layers', title: 'Page Selection', description: 'Click thumbnails to select individual pages for extraction' },
    { icon: 'Shield', title: 'No Upload', description: 'Processing happens locally — your files stay on your device' },
    { icon: 'Zap', title: 'Lightning Fast', description: 'Split PDFs in seconds with zero quality degradation' },
  ],
  compress: [
    { icon: 'Minimize2', title: 'Up to 80% Smaller', description: 'Reduce PDF file size dramatically while maintaining quality' },
    { icon: 'Eye', title: 'Quality Preserved', description: 'Intelligent compression keeps your documents looking perfect' },
    { icon: 'Shield', title: 'Secure Processing', description: 'Files are processed entirely in your browser — never uploaded' },
    { icon: 'Gauge', title: 'Instant Results', description: 'See compression results immediately after uploading' },
  ],
  rotate: [
    { icon: 'RotateCw', title: 'Per-Page Rotation', description: 'Rotate individual pages to different angles independently' },
    { icon: 'RefreshCw', title: 'Any Angle', description: 'Support for 90, 180, and 270 degree rotations' },
    { icon: 'Eye', title: 'Live Preview', description: 'See rotation changes in real-time before saving' },
    { icon: 'Shield', title: 'Zero Quality Loss', description: 'Rotation only changes orientation — content stays perfect' },
  ],
  'pdf-to-word': [
    { icon: 'FileText', title: 'Editable Output', description: 'Fully editable DOCX files compatible with Word, Google Docs, and more' },
    { icon: 'Layout', title: 'Formatting Preserved', description: 'Fonts, colors, tables, and images maintained from original PDF' },
    { icon: 'Zap', title: 'Instant Conversion', description: 'Convert PDF to Word in seconds right in your browser' },
    { icon: 'Shield', title: 'Private & Secure', description: 'Your documents never leave your device during conversion' },
  ],
  'word-to-pdf': [
    { icon: 'FileDown', title: 'Perfect Conversion', description: 'DOC/DOCX to PDF with complete formatting preservation' },
    { icon: 'Layout', title: 'Layout Maintained', description: 'Fonts, images, tables, and page layout stay exactly as designed' },
    { icon: 'Zap', title: 'Instant Results', description: 'Get your PDF in seconds with no quality loss' },
    { icon: 'Shield', title: 'Free & Private', description: 'No uploads — conversion happens entirely in your browser' },
  ],
  'jpg-to-pdf': [
    { icon: 'Image', title: 'Multiple Formats', description: 'Support for JPG, PNG, BMP, GIF, and TIFF image formats' },
    { icon: 'LayoutGrid', title: 'Multi-Image PDF', description: 'Combine multiple images into a single PDF document' },
    { icon: 'Settings', title: 'Customizable', description: 'Adjust orientation, margins, and page size before converting' },
    { icon: 'Shield', title: 'Original Quality', description: 'Images are embedded at full resolution with no compression' },
  ],
  'pdf-to-jpg': [
    { icon: 'Image', title: 'High Resolution', description: 'Extract pages as crisp, clear JPG images at original quality' },
    { icon: 'Layers', title: 'Individual Pages', description: 'Download specific pages or extract the entire document' },
    { icon: 'Zap', title: 'Fast Extraction', description: 'Convert PDF pages to images in seconds' },
    { icon: 'Shield', title: 'No Server Upload', description: 'All processing happens locally in your browser' },
  ],
  'excel-to-pdf': [
    { icon: 'Table', title: 'Table Preserved', description: 'Spreadsheets, tables, and data structures maintained perfectly' },
    { icon: 'BarChart3', title: 'Charts Included', description: 'Embedded charts, graphs, and visual elements preserved in PDF' },
    { icon: 'Layers', title: 'Multi-Sheet', description: 'All worksheets included in the output PDF document' },
    { icon: 'Shield', title: 'Secure Conversion', description: 'Excel files processed locally without server uploads' },
  ],
  'ppt-to-pdf': [
    { icon: 'Presentation', title: 'Slide Layout', description: 'Each PowerPoint slide becomes a perfectly formatted PDF page' },
    { icon: 'Image', title: 'Visual Elements', description: 'Images, charts, and graphics preserved in the PDF output' },
    { icon: 'Zap', title: 'Quick Conversion', description: 'Convert presentations of any size in seconds' },
    { icon: 'Shield', title: 'Free to Use', description: 'Unlimited PowerPoint to PDF conversions at no cost' },
  ],
  'html-to-pdf': [
    { icon: 'Globe', title: 'URL Support', description: 'Paste any webpage URL to capture and convert to PDF' },
    { icon: 'Code', title: 'HTML Code', description: 'Paste raw HTML code to render as a downloadable PDF' },
    { icon: 'Layout', title: 'CSS Preserved', description: 'Full CSS styling support for pixel-perfect PDF output' },
    { icon: 'Shield', title: 'Secure Process', description: 'HTML processed locally — no data sent to external servers' },
  ],
  'pdf-to-excel': [
    { icon: 'Table', title: 'Table Extraction', description: 'Automatically detect and extract tables from PDF documents' },
    { icon: 'FileSpreadsheet', title: 'Editable XLSX', description: 'Output fully editable Excel spreadsheets you can modify' },
    { icon: 'Scan', title: 'OCR Support', description: 'Extract data from scanned PDFs using built-in OCR technology' },
    { icon: 'Shield', title: 'Private Processing', description: 'Data extraction happens entirely in your browser' },
  ],
  'pdf-to-ppt': [
    { icon: 'Presentation', title: 'Editable Slides', description: 'Each PDF page becomes a fully editable PowerPoint slide' },
    { icon: 'Layout', title: 'Layout Preserved', description: 'Visual elements, text, and formatting maintained from PDF' },
    { icon: 'Zap', title: 'Fast Conversion', description: 'Convert any PDF to PowerPoint slides in seconds' },
    { icon: 'Shield', title: 'Free Conversion', description: 'Unlimited PDF to PowerPoint conversions without registration' },
  ],
  'pdf-to-pdfa': [
    { icon: 'Archive', title: 'ISO Compliant', description: 'Converts to PDF/A following ISO 19005 standard' },
    { icon: 'Clock', title: 'Long-Term Archiving', description: 'Documents remain accessible and viewable for decades' },
    { icon: 'CheckCircle', title: 'Font Embedded', description: 'All fonts embedded to ensure consistent rendering over time' },
    { icon: 'Shield', title: 'Secure Process', description: 'Conversion happens locally with no external dependencies' },
  ],
  'pdf-to-markdown': [
    { icon: 'Hash', title: 'Clean Output', description: 'Extract text, headings, and structure into clean Markdown format' },
    { icon: 'Code', title: 'Developer Friendly', description: 'Perfect for README files, docs, and text-based workflows' },
    { icon: 'Layout', title: 'Structure Preserved', description: 'Headings, lists, links, and basic formatting maintained' },
    { icon: 'Shield', title: 'Private Conversion', description: 'Document content stays on your device during conversion' },
  ],
  'pdf-translator': [
    { icon: 'Languages', title: '50+ Languages', description: 'Translate PDFs into Spanish, French, Chinese, Arabic, and more' },
    { icon: 'Layout', title: 'Layout Preserved', description: 'Original formatting and visual elements maintained after translation' },
    { icon: 'Brain', title: 'AI-Powered', description: 'Advanced AI provides natural, accurate translations' },
    { icon: 'Shield', title: 'Secure Translation', description: 'Documents processed locally without server uploads' },
  ],
  watermark: [
    { icon: 'Type', title: 'Text Watermark', description: 'Add custom text watermarks with full formatting control' },
    { icon: 'Image', title: 'Image Watermark', description: 'Upload logos or images as watermarks on your PDF' },
    { icon: 'Sliders', title: 'Full Control', description: 'Customize font, size, color, opacity, and position' },
    { icon: 'Shield', title: 'Private Processing', description: 'Watermarking happens entirely in your browser' },
  ],
  'smart-watermark': [
    { icon: 'Layers', title: 'Batch Processing', description: 'Apply watermarks to multiple PDFs simultaneously' },
    { icon: 'Settings2', title: 'Precise Positioning', description: 'Set exact coordinates and rotation for perfect placement' },
    { icon: 'Sliders', title: 'Opacity Control', description: 'Fine-tune transparency from subtle to prominent' },
    { icon: 'Shield', title: 'Secure & Private', description: 'All files processed locally without uploads' },
  ],
  protect: [
    { icon: 'Lock', title: '256-bit AES', description: 'Bank-grade encryption protects your sensitive documents' },
    { icon: 'Key', title: 'Password Protection', description: 'Set passwords to control who can open your PDF' },
    { icon: 'ShieldCheck', title: 'Permission Controls', description: 'Restrict printing, copying, and editing independently' },
    { icon: 'Shield', title: 'Secure Process', description: 'Encryption happens locally — password never leaves your device' },
  ],
  unlock: [
    { icon: 'Unlock', title: 'Remove Restrictions', description: 'Remove password protection and access restrictions from PDFs' },
    { icon: 'Zap', title: 'Instant Unlock', description: 'Unlock your PDF in seconds after entering the password' },
    { icon: 'FileCheck', title: 'Content Preserved', description: 'All content remains intact — only the protection is removed' },
    { icon: 'Shield', title: 'Local Processing', description: 'PDF and password stay on your device throughout' },
  ],
  'password-check': [
    { icon: 'Shield', title: 'Strength Analysis', description: 'Get detailed analysis of your PDF password security level' },
    { icon: 'Clock', title: 'Crack Time Estimate', description: 'See how long it would take to crack your password' },
    { icon: 'Lightbulb', title: 'Improvement Tips', description: 'Receive actionable suggestions to strengthen weak passwords' },
    { icon: 'Lock', title: 'Secure Analysis', description: 'Password analysis happens entirely in your browser' },
  ],
  organize: [
    { icon: 'ArrowUpDown', title: 'Drag & Drop', description: 'Reorder pages by simply dragging thumbnails' },
    { icon: 'FilePlus', title: 'Add Pages', description: 'Import pages from other PDFs to combine documents' },
    { icon: 'Trash2', title: 'Delete Pages', description: 'Remove unwanted pages with a single click' },
    { icon: 'Eye', title: 'Visual Preview', description: 'See page thumbnails to identify content easily' },
  ],
  crop: [
    { icon: 'Crop', title: 'Precise Cropping', description: 'Trim PDF margins with pixel-perfect accuracy' },
    { icon: 'LayoutGrid', title: 'Standard Sizes', description: 'Crop to A4, Letter, Legal, or custom dimensions' },
    { icon: 'Layers', title: 'Batch Crop', description: 'Apply the same crop settings to all pages at once' },
    { icon: 'Eye', title: 'Visual Selection', description: 'Drag crop handles to visually define the area to keep' },
  ],
  compare: [
    { icon: 'GitCompare', title: 'Side-by-Side', description: 'View both documents simultaneously with highlighted differences' },
    { icon: 'Highlighter', title: 'Change Detection', description: 'Text additions, deletions, and modifications clearly marked' },
    { icon: 'Search', title: 'Detailed View', description: 'Zoom in to inspect specific changes in context' },
    { icon: 'Zap', title: 'Fast Comparison', description: 'Compare documents of any size in seconds' },
  ],
  ocr: [
    { icon: 'Scan', title: 'Text Recognition', description: 'Convert scanned documents into searchable, selectable text' },
    { icon: 'Globe', title: 'Multi-Language', description: 'OCR supports English, Spanish, French, Chinese, and many more languages' },
    { icon: 'Search', title: 'Searchable PDF', description: 'Make scanned PDFs fully searchable for quick content finding' },
    { icon: 'Shield', title: 'Local Processing', description: 'OCR runs entirely in your browser without server uploads' },
  ],
  'ocr-editable': [
    { icon: 'Pencil', title: 'Editable Output', description: 'Convert scans into fully editable text documents' },
    { icon: 'Scan', title: 'OCR Technology', description: 'Advanced text recognition preserves original document structure' },
    { icon: 'Layout', title: 'Layout Preserved', description: 'Page structure, columns, and formatting maintained' },
    { icon: 'Shield', title: 'Secure Process', description: 'All OCR processing happens locally in your browser' },
  ],
  repair: [
    { icon: 'Wrench', title: 'Fix Corruption', description: 'Repair damaged headers, broken references, and structural issues' },
    { icon: 'RefreshCw', title: 'Data Recovery', description: 'Recover readable content from broken or corrupted PDF files' },
    { icon: 'FileCheck', title: 'Structure Rebuild', description: 'Rebuild PDF structure to create a fully functional document' },
    { icon: 'Shield', title: 'Safe Process', description: 'Original file is not modified — a new repaired PDF is generated' },
  ],
  'scan-to-pdf': [
    { icon: 'Camera', title: 'Camera Capture', description: 'Use your device camera to capture documents instantly' },
    { icon: 'Crop', title: 'Auto-Crop', description: 'Automatic edge detection and document cropping' },
    { icon: 'Sparkles', title: 'Enhancement', description: 'Improve contrast, brightness, and sharpness automatically' },
    { icon: 'FileDown', title: 'Direct to PDF', description: 'Convert scans directly to PDF without intermediate steps' },
  ],
  'pdf-forms': [
    { icon: 'TextCursorInput', title: 'Fillable Forms', description: 'Create and fill interactive PDF form fields' },
    { icon: 'CheckSquare', title: 'Form Elements', description: 'Text fields, checkboxes, dropdowns, and signature fields' },
    { icon: 'Pen', title: 'Digital Signatures', description: 'Add signature fields for electronic signing' },
    { icon: 'Shield', title: 'Standard Compatible', description: 'Forms work with Adobe Reader, Preview, and all PDF readers' },
  ],
  redact: [
    { icon: 'Eraser', title: 'Permanent Removal', description: 'Redacted content is completely removed, not just hidden' },
    { icon: 'Search', title: 'Text Search', description: 'Find and redact specific words or phrases throughout the document' },
    { icon: 'Highlighter', title: 'Area Selection', description: 'Select specific areas on any page to redact' },
    { icon: 'Shield', title: 'Secure Redaction', description: 'No traces of redacted content remain in the output PDF' },
  ],
  esignature: [
    { icon: 'PenTool', title: 'Draw Signature', description: 'Create your signature by drawing directly in the browser' },
    { icon: 'Type', title: 'Type Signature', description: 'Choose from handwriting-style fonts for a typed signature' },
    { icon: 'FileCheck', title: 'Legally Valid', description: 'eSignatures comply with ESIGN Act, eIDAS, and global standards' },
    { icon: 'Send', title: 'Request Signatures', description: 'Send documents to others for electronic signature collection' },
  ],
  'page-numbers': [
    { icon: 'Hash', title: 'Multiple Formats', description: 'Arabic numerals, Roman numerals, and custom formats supported' },
    { icon: 'Layout', title: 'Flexible Positioning', description: 'Place numbers at top, bottom, left, center, or right' },
    { icon: 'Type', title: 'Custom Fonts', description: 'Choose font family, size, and color for page numbers' },
    { icon: 'Shield', title: 'Free Tool', description: 'Add unlimited page numbers to your PDFs at no cost' },
  ],
  'delete-pages': [
    { icon: 'Trash2', title: 'Quick Deletion', description: 'Remove unwanted pages with a single click' },
    { icon: 'Layers', title: 'Multi-Select', description: 'Select and delete multiple pages simultaneously' },
    { icon: 'Eye', title: 'Visual Preview', description: 'Thumbnail view to confirm pages before deletion' },
    { icon: 'Shield', title: 'Safe Process', description: 'Preview and confirm before applying any changes' },
  ],
  summarizer: [
    { icon: 'Brain', title: 'AI-Powered', description: 'Google Gemini AI analyzes and summarizes your document' },
    { icon: 'List', title: 'Multiple Formats', description: 'Brief summaries, detailed overviews, bullet points, or study questions' },
    { icon: 'Zap', title: 'Instant Results', description: 'Get comprehensive summaries in seconds' },
    { icon: 'Globe', title: 'Multi-Language', description: 'Summarize documents in English, Spanish, French, and more' },
  ],
  translate: [
    { icon: 'Languages', title: '50+ Languages', description: 'Translate into major world languages with AI precision' },
    { icon: 'Layout', title: 'Layout Preserved', description: 'Original formatting and visual elements maintained' },
    { icon: 'Brain', title: 'AI Translation', description: 'Natural, accurate translations powered by advanced AI' },
    { icon: 'Shield', title: 'Secure Process', description: 'Documents processed locally without external servers' },
  ],
  'resume-builder': [
    { icon: 'LayoutTemplate', title: 'Professional Templates', description: 'Choose from modern, ATS-friendly resume templates' },
    { icon: 'Eye', title: 'Live Preview', description: 'See your resume update in real-time as you edit' },
    { icon: 'FileDown', title: 'PDF Export', description: 'Download your completed resume as a high-quality PDF' },
    { icon: 'Settings', title: 'Fully Customizable', description: 'Modify colors, fonts, sections, and layout to your preference' },
  ],
  workflows: [
    { icon: 'Workflow', title: 'Chain Tools', description: 'Connect multiple PDF tools into a single automated pipeline' },
    { icon: 'Save', title: 'Save & Reuse', description: 'Create once and run the same workflow anytime' },
    { icon: 'Layers', title: 'Batch Processing', description: 'Process multiple documents through the same workflow' },
    { icon: 'Zap', title: 'Automated', description: 'Eliminate repetitive manual tasks with workflow automation' },
  ],
  templates: [
    { icon: 'LayoutTemplate', title: 'Professional Design', description: 'Expertly crafted templates for every document type' },
    { icon: 'Download', title: 'Free Downloads', description: 'All templates available at no cost for any use' },
    { icon: 'Pencil', title: 'Customizable', description: 'Edit text, images, and layout to match your needs' },
    { icon: 'FileDown', title: 'PDF Export', description: 'Download completed templates as print-ready PDFs' },
  ],
};

export const toolGuides: Record<string, { title: string; steps: { icon: string; title: string; description: string }[] }> = {
  'pdf-to-word': {
    title: 'How to Convert PDF to Word (Step-by-Step)',
    steps: [
      { icon: '1', title: 'Upload Your PDF', description: 'Click the upload area above or drag and drop your PDF file directly onto the page. DocuPDF accepts files of any size — there are no document limits.' },
      { icon: '2', title: 'Wait for Processing', description: 'The conversion happens automatically in your browser using client-side technology. Your PDF is analyzed page by page — text, tables, images, and formatting are all extracted.' },
      { icon: '3', title: 'Review & Download', description: 'Once conversion completes, your editable DOCX file is ready for download. Click the download button to save the converted Word document to your device.' },
      { icon: '4', title: 'Open in Any Word Processor', description: 'The output DOCX file works in Microsoft Word, Google Docs, LibreOffice, or any compatible word processor. All fonts, colors, tables, and images are preserved from your original PDF.' },
    ],
  },
  'word-to-pdf': {
    title: 'How to Convert Word to PDF (Step-by-Step)',
    steps: [
      { icon: '1', title: 'Upload Your Document', description: 'Select your DOC or DOCX file using the upload area, or drag and drop it onto the page. DocuPDF supports all Word versions including .doc and .docx formats.' },
      { icon: '2', title: 'Instant Conversion', description: 'The tool processes your Word document entirely in your browser. Fonts, images, tables, and page layouts are carefully converted to the PDF format.' },
      { icon: '3', title: 'Download Your PDF', description: 'Your PDF is ready instantly. Click download to save your file — all formatting, images, and text remain exactly as they appeared in the original Word document.' },
    ],
  },
};

export const toolRelatedTools: Record<string, string[]> = {
  merge: ['split', 'compress', 'organize', 'delete-pages'],
  split: ['merge', 'compress', 'organize', 'delete-pages'],
  compress: ['merge', 'split', 'pdf-to-word', 'protect'],
  rotate: ['crop', 'organize', 'page-numbers', 'watermark'],
  'pdf-to-word': ['word-to-pdf', 'pdf-to-excel', 'pdf-to-ppt', 'ocr'],
  'word-to-pdf': ['pdf-to-word', 'compress', 'protect', 'page-numbers'],
  'jpg-to-pdf': ['pdf-to-jpg', 'pdf-to-word', 'compress', 'merge'],
  'pdf-to-jpg': ['jpg-to-pdf', 'ocr', 'pdf-to-word', 'pdf-to-excel'],
  'excel-to-pdf': ['pdf-to-excel', 'ppt-to-pdf', 'compress', 'protect'],
  'ppt-to-pdf': ['pdf-to-ppt', 'excel-to-pdf', 'compress', 'merge'],
  'html-to-pdf': ['pdf-to-word', 'pdf-to-markdown', 'compress', 'watermark'],
  'pdf-to-excel': ['excel-to-pdf', 'pdf-to-word', 'ocr', 'pdf-to-ppt'],
  'pdf-to-ppt': ['ppt-to-pdf', 'pdf-to-word', 'compress', 'merge'],
  'pdf-to-pdfa': ['protect', 'compress', 'redact', 'esignature'],
  'pdf-to-markdown': ['html-to-pdf', 'pdf-to-word', 'ocr-editable', 'summarizer'],
  'pdf-translator': ['translate', 'ocr', 'pdf-to-word', 'summarizer'],
  watermark: ['smart-watermark', 'protect', 'page-numbers', 'rotate'],
  'smart-watermark': ['watermark', 'protect', 'page-numbers', 'organize'],
  protect: ['unlock', 'password-check', 'redact', 'esignature'],
  unlock: ['protect', 'password-check', 'pdf-to-word', 'organize'],
  'password-check': ['protect', 'unlock', 'redact', 'repair'],
  organize: ['merge', 'split', 'delete-pages', 'rotate'],
  crop: ['rotate', 'organize', 'page-numbers', 'pdf-to-jpg'],
  compare: ['pdf-to-word', 'pdf-to-excel', 'ocr', 'summarizer'],
  ocr: ['ocr-editable', 'pdf-to-word', 'pdf-to-excel', 'pdf-translator'],
  'ocr-editable': ['ocr', 'pdf-to-word', 'pdf-to-excel', 'repair'],
  repair: ['ocr', 'ocr-editable', 'compress', 'pdf-to-word'],
  'scan-to-pdf': ['ocr', 'compress', 'merge', 'protect'],
  'pdf-forms': ['esignature', 'protect', 'page-numbers', 'redact'],
  redact: ['protect', 'esignature', 'pdf-to-word', 'unlock'],
  esignature: ['protect', 'pdf-forms', 'redact', 'page-numbers'],
  'page-numbers': ['watermark', 'protect', 'merge', 'organize'],
  'delete-pages': ['split', 'organize', 'merge', 'crop'],
  summarizer: ['translate', 'pdf-translator', 'ocr', 'pdf-to-markdown'],
  translate: ['pdf-translator', 'summarizer', 'ocr', 'pdf-to-word'],
  'resume-builder': ['templates', 'pdf-forms', 'esignature', 'watermark'],
  workflows: ['merge', 'compress', 'protect', 'watermark'],
  templates: ['resume-builder', 'pdf-forms', 'esignature', 'page-numbers'],
};
